export const CardsOrdersData = [
    {
        id: 1,
        clientName: "Prueba",
        phoneNumber: "999-999-999",
        address: "Villa de sol",
        vehicleSerialNumber: "2ASS2VA",
        brand: "Toyota",
        entryDate: "2023-06-01",
        fuelLevel: 75,
        licensePlate: "ABC123",
        model: "Corolla",
        mileage: 15000,
        color: "Red",
        vehicleObservations: "Perfectas condiciones",
        vehicleDescription: "Sedan, 4 puertas",
        exitDate: "2023-06-10",
        valuableItems: "Lentes"
    }, 
    {
        id: 2,
        clientName: "Luna",
        phoneNumber: "999-999-999",
        address: "Villa de luna",
        vehicleSerialNumber: "1ASC4VD",
        brand: "Audi",
        entryDate: "2023-08-05",
        fuelLevel: 82,
        licensePlate: "ABC123",
        model: "A5",
        mileage: 1000,
        color: "Plata",
        vehicleObservations: "Un pequeño golpe",
        vehicleDescription: "4 puertas y quema-cocos",
        exitDate: "2023-08-10",
        valuableItems: "Anillo"
    }, 
    {
        id: 3,
        clientName: "Canelo",
        phoneNumber: "999-999-999",
        address: "Villa de luna",
        vehicleSerialNumber: "1ASC4VD",
        brand: "Audi",
        entryDate: "2023-08-05",
        fuelLevel: 82,
        licensePlate: "ABC123",
        model: "A5",
        mileage: 1000,
        color: "Plata",
        vehicleObservations: "Un pequeño golpe",
        vehicleDescription: "4 puertas y quema-cocos",
        exitDate: "2023-08-10",
        valuableItems: "Anillo"
    }, 
    {
        id: 4,
        clientName: "Junior",
        phoneNumber: "999-999-999",
        address: "Villa de luna",
        vehicleSerialNumber: "1ASC4VD",
        brand: "Audi",
        entryDate: "2023-08-05",
        fuelLevel: 82,
        licensePlate: "ABC123",
        model: "A5",
        mileage: 1000,
        color: "Plata",
        vehicleObservations: "Un pequeño golpe",
        vehicleDescription: "4 puertas y quema-cocos",
        exitDate: "2023-08-10",
        valuableItems: "Anillo"
    }, 
    
];
